### ISSUE TITLE
Allow reuse of same node (i.e. multiple arrows)

### ISSUE THREAD

**Issue by bfelbo** [jimblackler/treefun#3]
Great little tool, thanks!

I'm trying to use it for [Critical Path Analysis](https://en.wikipedia.org/wiki/Critical_path_method) for project management, essentially dependency mapping. As part of that, I need the ability to reuse nested nodes and have multiple arrows originating from the reused node. For instance, the data below should only generate 4 nodes with `b` having arrows to both `a` and `c`.

```
a
 b
c
 b
 d
```

However, instead `b` is plotted twice as seen below.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/23178145/201489510-bb9ad56b-2111-43ff-905b-30cff5db46cc.png">

This is obviously a contrived example. For the actual use case, this functionality would be used many times in a much larger diagram.

**Comment by jimblackler** [comment]
I appreciate the use case. 

This would relax the requirement for a strict tree into one of a directed graph. However only certain graphs could be rendered with this algorithm. For a node to have two parents the parents must have the same distance to the root (depth) (otherwise they'd be on different rows). In addition each node could have a maximum of two children with multiple parents (otherwise lines would cross).

If people would be OK with those restrictions it could be done.

**Comment by bfelbo** [comment]
Thanks for your response. Those restrictions make sense given the algorithm, but would they would limit the applicability (at least for me) so perhaps not worth you spending effort to implement it then.
